---
title: "Explore of CES"
author: "Feixue Han"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
references: "reference.bib"
tags: ["R Markdown", "plot", "regression"]
---
https://github.com/hanfeixue212/sta304-draft-1

# Abstract
We investigated the 2019 CES data. The result of the survey data shows that the substantial influence on the Canadian Election on the Canadian president candidates.  Voting and elections are the most basic elements of democracy. The CES has recorded Canadians’ political behaviour and altitudes and the preference on the key political issues. The study aims to explore the important results of the Canadian election if most of the citizen vote for the election by using logistic model and poststratification method. 
# Introduction
In main idea of the Canadian election survey is to show the main reasons for they way people vote for the candidates. According to this survey, it also invests the similarity and the difference of the voting in Canada and in other country. Furthermore, the result of the survey contributes to the science knowledge of the motivation of the voters and the meaning of the election. Moreover, the information of altitude and opinions of the Canadian citizens on social, economic, and political issues can be provided to public. 
In the survey, we analysis the subset of 2016 statistic Canada of Education Census. The table provides education data from Census of population according tot eh geographic and year. 
# data

# data clean

# data selection

# model

# model specifies

# ## Post-Stratification

# result

# data discussion

# weekness

# next step

# appendix

# Reference
